### PR TITLE
Install katex and add basic implementation to description

### LINKED ISSUE #269: Add mathjax support to text input boxes boxes
Would be nice to support latex in submission boxes for things like the abstract on the submission page or method description. Might be possible to use in node mathjaxs: http://docs.mathjax.org/en/latest/server/components.html

### PR DESCRIPTION
**Pull request by Aaron-Robertson**
Fixes #269

### CODE REVIEW

**Comment by Aaron-Robertson** [comment]
@WrathfulSpatula let's walk through further implementation details and testing when you get a chance, but we're getting close!

**Comment by WrathfulSpatula** [comment]
@Aaron-Robertson This looks good! What about the "detail view" descriptions, though? You've covered the "synopsis" box view for submissions, but that same text (without truncation) is displayed in the submission detail view, as well.

**Comment by Aaron-Robertson** [comment]
Alright @WrathfulSpatula, I think we're good to go here! Let me know if you have any other feedback 🚀

**Review by WrathfulSpatula — APPROVED** [review]
Looks great! Thank you so much!

**Pull request merged**
