### PR TITLE
add description of metriq to readme

### PR DESCRIPTION
**Pull request by natestemen**
Does what is says on the 🥫. I've removed the create react app boilerplate. Let me know if you want to keep that for documentation purposes and I can add it back. 

fixes https://github.com/unitaryfund/metriq-app/issues/647

### CODE REVIEW

**Comment by vprusso** [comment]
Approving. I think the only thing that I wonder about is whether we stylize the capital "Q"and the end of "MetriQ" anywhere else and whether that convention is something we should include here or not.

**Review by vprusso — APPROVED** [review]

**Comment by natestemen** [comment]
Good catch. Consistency is key. Just let me know what is preferred, an we can go with that throughout the README.

**Comment by vprusso** [comment]
I think the way we generally stylize things is just "Metriq". Perhaps we should aim to keep it like that if you agree. Thanks again for the PR! Feel free to merge when you feel it is ready.

**Review by WrathfulSpatula — COMMENTED** [review]
LGTM, by the way! Thanks, Nate!

**Pull request merged**
