### PR TITLE
Adding newsletter to footer

### PR DESCRIPTION
**Pull request by crazy4pi314**
Adds a field in the footer to sign up for the mailchimp list

### CODE REVIEW

**Review by WrathfulSpatula — CHANGES_REQUESTED** [review]
Thank you for the pull request, and thank you for setting up the mailing list!

The form field in the hosted app doesn't accept text input, for me. We need React.js-compatible integration, rather than pure HTML. We could adapt the footer form field to register its state with the view component class, or Mailchimp might have a tag example for Sass/React.js.

Either you or I could debug this, but it's not ready for merge. Feel free to commit on the PR branch, but check whether you can input text in the hosted app form field, (or let me know if you could use help getting a debug hosting environment set up).

**Comment by WrathfulSpatula** [comment]
The reason why text input is blocked is probably that this is in the Sass view component definition. I'm relatively new to Sass, myself, but we could likely abstract the form field as a reusable React.js component, (or delve into Sass, as appropriate).

**Comment by crazy4pi314** [comment]
This tutorial might help? https://lgille.medium.com/create-your-first-mailchimp-signup-using-react-js-for-your-marketing-campaign-b85df74acf33

Also I generated Mail chimp's most basic embed, I am not sure if this would solve the problem though...
```
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://fund.us18.list-manage.com/subscribe/post?u=104796c75ced8350ebd01eebd&amp;id=a2c9e5ac2a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div hidden="true"><input type="hidden" name="tags" value="2099722"></div>
	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_104796c75ced8350ebd01eebd_a2c9e5ac2a" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot">
                <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
                <p class="brandingLogo"><a href="http://eepurl.com/hU7M8X" title="Mailchimp - email marketing made easy and fun"><img src="https://eep.io/mc-cdn-images/template_images/branding_logo_text_light_dtp.svg"></a></p>
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by WrathfulSpatula** [comment]
@crazy4pi314 I'll take a look today, after the engineering meeting. Thank you!

**Review by WrathfulSpatula — APPROVED** [review]
@crazy4pi314 I replaced the HTML form with the React.js component that Mailchimp is so kind to provide! I'm going to turn the review back around to you, to see what I did with your branch.

**Comment by WrathfulSpatula** [comment]
Actually, I can't request a review from the PR author. However, take a look and let me know if you notice any issues. Merging!

**Pull request merged**
